spring:
  thymeleaf:
    cache: true
  jpa:
    hibernate:
      #none/validate/update/create-drop
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://gps2track.c549jops6x3b.sa-east-1.rds.amazonaws.com:5432/gps2track
    username: prg2t
    password: Cj27OqAsHU5i9eQgz24N
